version: "3.9"

services:
  api_gateway:
    image: nginx:latest
    container_name: api_gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - auth_service
    networks:
      - micro_net

  auth_service:
    build: ./auth_service
    container_name: auth_service
    command: gunicorn auth_service_project.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./auth_service:/app
    expose:
      - "8001"
    depends_on:
      - mysql_database
    networks:
      - micro_net

  mysql_database:
    image: mysql:8
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: Root@1234
      MYSQL_DATABASE: erpData
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - micro_net

volumes:
  mysql_data:

networks:
  micro_net:
    driver: bridge
